### ISSUE TITLE
Unable to run st2 CLI after bootstrapping

### ISSUE THREAD

**Issue by lakshmi-kannan** [enykeev/st2testground#1]
```
vagrant@st2packages:~$ st2 --debug action list
ERROR: HTTPConnectionPool(host='127.0.0.1', port=9101): Max retries exceeded with url: /v1/actions (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f70d68c7690>: Failed to establish a new connection: [Errno 111] Connection refused',))

CLI settings:
----------------
Config file path: /home/vagrant/.st2/config
Client settings:
----------------
ST2_BASE_URL: http://127.0.0.1
ST2_AUTH_URL: http://127.0.0.1:9100
ST2_API_URL: http://127.0.0.1:9101/v1
ST2_AUTH_TOKEN: None

Proxy settings:
---------------
HTTP_PROXY:
HTTPS_PROXY:

Traceback (most recent call last):
  File "/usr/share/python/st2/local/lib/python2.7/site-packages/st2client/shell.py", line 353, in run
    args.func(args)
  File "/usr/share/python/st2/local/lib/python2.7/site-packages/st2client/commands/resource.py", line 237, in run_and_print
    instances = self.run(args, **kwargs)
  File "/usr/share/python/st2/local/lib/python2.7/site-packages/st2client/commands/resource.py", line 41, in decorate
    return func(*args, **kwargs)
  File "/usr/share/python/st2/local/lib/python2.7/site-packages/st2client/commands/resource.py", line 259, in run
    return self.manager.get_all(**filters)
  File "/usr/share/python/st2/local/lib/python2.7/site-packages/st2client/models/core.py", line 35, in decorate
    return func(*args, **kwargs)
  File "/usr/share/python/st2/local/lib/python2.7/site-packages/st2client/models/core.py", line 187, in get_all
    response = self.client.get(url=url, params=params, **kwargs)
  File "/usr/share/python/st2/local/lib/python2.7/site-packages/st2client/utils/httpclient.py", line 33, in decorate
    return func(*args, **kwargs)
  File "/usr/share/python/st2/local/lib/python2.7/site-packages/st2client/utils/httpclient.py", line 44, in decorate
    return func(*args, **kwargs)
  File "/usr/share/python/st2/local/lib/python2.7/site-packages/st2client/utils/httpclient.py", line 68, in get
    response = requests.get(self.root + url, **kwargs)
  File "/usr/share/python/st2/local/lib/python2.7/site-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/share/python/st2/local/lib/python2.7/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/share/python/st2/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python/st2/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python/st2/local/lib/python2.7/site-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=9101): Max retries exceeded with url: /v1/actions (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f70d68c7690>: Failed to establish a new connection: [Errno 111] Connection refused',))
vagrant@st2packages:~$ cat /home/vagrant/.st2/config
cat: /home/vagrant/.st2/config: No such file or directory
vagrant@st2packages:~$
```

**Comment by lakshmi-kannan** [comment]
So I am not sure if this the way we want to "ship" the new installer so this issue might be a moot point. I can verify that I can hit the APIs just fine and st2web works.
